// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://rdywfmfkfqnnvswhajab.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJkeXdmbWZrZnFubnZzd2hhamFiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjEzNDk2NTIsImV4cCI6MjA3NjkyNTY1Mn0.fwKBeHs22jPY1beHJtiuX63nNo-3Hbj8EcmWp8fnBwc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);